


<div class="columns">
    <div class="column">
        <h2 class="is-size-2">Libros en la base de Datos</h2>
        <a class="button is-success" href="#">Nuevo&nbsp;<i class="fa fa-plus"></i></a>
        <table class="table is-hoverable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Imagen</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody id="cuerpoTabla">
            <?php foreach($listLibros->items as $item) : ?>    
            <tr>
                
                    <th><?= $item->id; ?>
                   
                    </th>
                    <th><?= $item->nombrelib; ?></th>
                    <th><?= $item->price; ?></th>
                    <th><?= $item->imagen; ?></th>
                    <th>
                        <?= Html::linkAction("edit/$item->id/", 'Editar', 'class="button small is-danger is-light"') ?> 
                        <input class="button small is-primary is-light" type="reset" value="Eliminar"> 
                    </th>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>


<div class="content">
  <?php View::content() ?> 

      <?= Html::linkAction("edit/$item->id/", 'Editar') ?> 
      <?= Html::linkAction("del/$item->id/", 'Borrar') ?> 
      


